[customizations.installer.kickstart]
contents = """

# --- install container
%post
bootc switch --mutate-in-place --transport registry ghcr.io/nfg42/ucore_server:latest
%end

"""

[customizations.installer.modules]
enable = [
  "org.fedoraproject.Anaconda.Modules.Storage",
  "org.fedoraproject.Anaconda.Modules.Runtime",
  "org.fedoraproject.Anaconda.Modules.Network",
  "org.fedoraproject.Anaconda.Modules.Services",
  "org.fedoraproject.Anaconda.Modules.Users",
  "org.fedoraproject.Anaconda.Modules.Timezone",
  "org.fedoraproject.Anaconda.Modules.Security"
]
disable = [
  "org.fedoraproject.Anaconda.Modules.Subscription"
]
