- name: Bootstrap new host
  hosts: bootstrap
  gather_facts: true
  vars:
    this_uuid: "{{ ansible_product_uuid | hash('sha256') | regex_replace('^(.{8}).*', '\\1') }}"
  roles:
    - role: bootstrap
    - role: secrets_tools

- name: Setup compute host
  hosts: compute
  gather_facts: true
  roles:
    - role: common
    #- role: secrets_tools
    - role: sshd_hardening         # then apply ssh hardening drop-in
