- name: Bootstrap new host
  hosts: bootstrap
  gather_facts: true
  vars:
    this_uuid: "{{ ansible_product_uuid | hash('sha256') | regex_replace('^(.{8}).*', '\\1') }}"
  roles:
    - bootstrap

- name: Setup compute host
  hosts: compute
  gather_facts: true
  roles:
    - role: common
#    - role: btrfs
    - role: manage_disks_nas
      tags:
        - manage_disks
        - btrfs

    - role: configure_mergerfs
      tags:
        - configure_mergerfs
        - mergerfs

    - role: configure_snapraid
      tags:
        - configure_snapraid
        - snapraid