_hostname: core1

admin_user: ladmin
admin_group: ladmin

encrypt_pass: $6$LhbC5.gHBFRXV1um$7D/2cP6g8fTjddeqnbrOCsyBgf2CP2mPzWtd7Vh3GLW5ZDahD9atPSQoalBOF9db9/L7xGNeYKXk9wblcDHCQ1

admin_authorized_keys:
  - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHr70B4/i9XjDzxsxHrn1+lyJ/OrHvfJQL4gwvNi3xOh core@core1"
  - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJ8NmEYncnByvHbkQE/hVtlQNSUDf6HHpRhd0kWxw/ca desktop"
  - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDOFcsV2LsUWMuTFtBTmUUXDLRoAAeoy1Dvdqtj6Sula phone" 
  - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICPJVpOzHYwWVUJnphKXOfBeH/l8npAbkX+bkQr88d3B laptop"
  - "ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQBdzWgdLF/OtB6Ho9QWyCJ80OLOoenkm+tazPxYc8bLcko0YDNxTJ5xzZ1z/VTfUTO6DOUzBU7uq+AuMaAC/fmUJDtizkDwMwjxCWrdsFgVu0OZxkjMjQLnTdLdUnDHpq4wmVfHPCUnO/Tl5McHOLoynQP4vgkgdUkP3GogxHUnEp2FbavJ9i6mFuZs/vfdYOqU5LW+RP10XXyflWUX1RiSoiWwCsGC3i40KwE8Vo5Vu9g8AMY0f1PVZDndwAJXdZ4bQ0s1LKNO/Uk6qvAEqVAAf9DqJUHFBofOVM7rRyImjeUeB22eE6DS352iptkJs8Buf4gmDv6syjLni69z9chp rsa-test"
  
