---
# Each handler listens to the same event name and runs in order.
- name: Validate sshd config (sshd -t)
  listen: "Validate and reload sshd"
  ansible.builtin.command: sshd -t
  changed_when: false
  become: true

- name: Reload sshd
  listen: "Validate and reload sshd"
  ansible.builtin.systemd:
    name: sshd
    state: reloaded
  when: sshd_reload_only | default(true)
  become: true

- name: Restart sshd
  listen: "Validate and reload sshd"
  ansible.builtin.systemd:
    name: sshd
    state: restarted
  when: not (sshd_reload_only | default(true))
  become: true
