---
- name: "Validate and reload sshd"
  listen: "Validate and reload sshd"
  block:
    - name: "Validate sshd config (sshd -t)"
      ansible.builtin.command: sshd -t
      changed_when: false
      become: true

    - name: "Reload sshd"
      ansible.builtin.systemd:
        name: sshd
        state: reloaded
      when: sshd_reload_only
      become: true

    - name: "Restart sshd"
      ansible.builtin.systemd:
        name: sshd
        state: restarted
      when: not sshd_reload_only
      become: true
  rescue:
    - name: "Abort due to invalid sshd config"
      ansible.builtin.fail:
        msg: "Invalid sshd config; not reloading."
